// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw8iGeq24Q6prAWeBTDPsyOdDj4FV2rfc',
    appId: '1:169491787982:web:efd2b199ef123526b2a09f',
    messagingSenderId: '169491787982',
    projectId: 'entrega-app-victor',
    authDomain: 'entrega-app-victor.firebaseapp.com',
    storageBucket: 'entrega-app-victor.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR568rAke8pDJ_YZ-KNyCpdQ8cLL1WDtg',
    appId: '1:169491787982:android:e16b641842290da6b2a09f',
    messagingSenderId: '169491787982',
    projectId: 'entrega-app-victor',
    storageBucket: 'entrega-app-victor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr9gTUXUKwacVQ1nldMU3uuusHiBKVf70',
    appId: '1:169491787982:ios:df1e189b2dc369b6b2a09f',
    messagingSenderId: '169491787982',
    projectId: 'entrega-app-victor',
    storageBucket: 'entrega-app-victor.firebasestorage.app',
    iosBundleId: 'com.example.entregaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr9gTUXUKwacVQ1nldMU3uuusHiBKVf70',
    appId: '1:169491787982:ios:df1e189b2dc369b6b2a09f',
    messagingSenderId: '169491787982',
    projectId: 'entrega-app-victor',
    storageBucket: 'entrega-app-victor.firebasestorage.app',
    iosBundleId: 'com.example.entregaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw8iGeq24Q6prAWeBTDPsyOdDj4FV2rfc',
    appId: '1:169491787982:web:bfcbfec8dd881ffeb2a09f',
    messagingSenderId: '169491787982',
    projectId: 'entrega-app-victor',
    authDomain: 'entrega-app-victor.firebaseapp.com',
    storageBucket: 'entrega-app-victor.firebasestorage.app',
  );
}
